UKHomeOffice/hocs-audit

- src/main/java/uk/gov/digital/ho/hocs/audit/export/DataExportResource.java
- src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java
- src/main/java/uk/gov/digital/ho/hocs/audit/export/dto/AuditPayload.java
- src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportIntTest.java
- src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportServiceTest.java
move case type to path to enable case type permissions
> Add user allocations

- .drone.yml
- src/main/java/uk/gov/digital/ho/hocs/audit/AuditDataService.java
- src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java
Merged WCS and changed pipeline.
> Hocs 1410 audit pipeline

- .drone.yml
- Dockerfile
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/resources/application.properties
- src/test/resources/application.properties
Upgrade Java version from 8 to 11
> HOCS-1513 : audit service application upgrade to Java 11

- build.gradle
Upgrading all the Javas 8 -> 11
> HOCS-1513 : audit service application upgrade to Java 11, more

- src/main/resources/application.properties
> HOCS-1513 : audit service application upgrade to Java 11, schema

- .drone.yml
- Dockerfile
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/resources/application.properties
- src/test/resources/application.properties
> Revert Java 11 upgrade, all is forgiven Java 8

- src/main/java/uk/gov/digital/ho/hocs/audit/export/DataExportResource.java
- src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java
- src/main/java/uk/gov/digital/ho/hocs/audit/export/infoclient/InfoClient.java
- src/main/java/uk/gov/digital/ho/hocs/audit/export/infoclient/dto/TopicTeamDto.java
- src/test/java/uk/gov/digital/ho/hocs/audit/export/infoclient/InfoClientTest.java
New extract that exports topics and their linked teams for given case type.
> HOCS-1938 : export topics and teams

- src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java
- src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportType.java
- src/main/java/uk/gov/digital/ho/hocs/audit/export/dto/AuditPayload.java
- src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportServiceTest.java
New export type that extracts case notes as CSV
> HOCS-1966 : export Case Notes for MI

- src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java
- src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportServiceTest.java
- src/test/resources/headers.config
Conversion mechanism added to case notes extract.
Tests added for verification.
> HOCS-2150 Convert Case Notes

- src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java
- src/main/java/uk/gov/digital/ho/hocs/audit/export/infoclient/dto/TopicDto.java
- src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/audit/export/infoclient/InfoClientTest.java
This PR along with https://github.com/UKHomeOffice/hocs-info-service/pull/255 addresses HOCS-2262-Add active/inactive column to Topics extract
Changes in this PR:
* Add active column to topics extract csv
>  HOCS-2262-Add active column to topics extract json

- src/main/java/uk/gov/digital/ho/hocs/audit/application/ZonedDateTimeConverter.java
- src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java
- Add additional (temporary) logging to track changes to timestamp on case extract to help find bug in prod
> HOCS-2424 Add temporary timestamp logging for extract

- .drone.yml
This is the counterpart to https://github.com/UKHomeOffice/hocs-info-service/pull/250. Apparently we forgot to do audit.
> Push non-master branches to image registry

- src/main/java/uk/gov/digital/ho/hocs/audit/export/CustomExportService.java
- src/test/java/uk/gov/digital/ho/hocs/audit/export/CustomExportServiceTest.java
* Protect refresh endpoint by checking roles
> HOCS-2310 Running custom reports takes too long

- .drone.yml
* Update drone spec to fix push issue
> HOCS-3783 - Update audit drone spec

- src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java
- src/main/java/uk/gov/digital/ho/hocs/audit/export/dto/AuditPayload.java
- src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportServiceTest.java
Added the missing organisation field from the extract for correspondents
> HOCS-3936 add organisation to extract details

- src/main/resources/db/migration/postgresql/V1_4__ADD_TIMESTAMP_INDEX.sql
Create an index that is missing identified as part of the live service investigation for HOCS-4100
> HOCS-4100 Create an index on timestamp in audit_data

- build.gradle
Update gradle dependencies where applicable.
> HOCS-4085: update dependencies

- kube/deploy.sh
- kube/kd/deployment.yaml
- src/main/resources/db/migration/postgresql/V1_5__ADD_CASE_UUID_TYPE_INDEX.sql
Hocs-4100
This commit brings the kube config in to line with what is in prod after making changes to support a live service investigation.
Specifically: 
* A new index
*  Updated kube config
> Hocs 4100 index and kube

- .drone.yml
- build.gradle
- docker-compose.yml
At the moment we are using unknown versions of Postgres in the build, this commit moves drone and docker-compose over to using the official images.
> HOCS-4212 - Upgrade Postgres version used in the project

- .drone.yml
Let's accept the risk of pulling latest and it being broken Vs us having to track changes
> 👷 HOCS-4660 Update the version of Sonarqube

- src/main/java/uk/gov/digital/ho/hocs/audit/export/parsers/DataParserFactory.java
Added BF2 case type for exporting Interests.
> HOCS-4398 add abilityy to export case type BF2 Interest

- src/main/resources/db/migration/postgresql/V1_7__DETACH_OLD_VEIWED_PARTITIONS.sql
Remove (but retain) *_viewed messages as they aren't used in case timelines or extracts
> HOCS-4940: Remove (but retain) *_viewed messages

- src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepository.java
```
hocsprodaudit=> explain analyze
hocsprodaudit-> SELECT a.*
hocsprodaudit-> FROM audit_event a
hocsprodaudit->  WHERE 
hocsprodaudit-> a.case_uuid = 'e3ef6cd0-381d-49ac-8cdd-02668f80bfa2' 
hocsprodaudit-> AND a.type in ('CASE_CREATED', 'CASE_TOPIC_CREATED', 'CASE_COMPLETED', 'CASE_TOPIC_DELETED', 'STAGE_ALLOCATED_TO_TEAM', 'STAGE_CREATED', 'STAGE_RECREATED','STAGE_COMPLETED','STAGE_ALLOCATED_TO_USER','CORRESPONDENT_DELETED','CORRESPONDENT_CREATED','CORRESPONDENT_UPDATED','DOCUMENT_CREATED','DOCUMENT_DELETED', 'APPEAL_UPDATED', 'APPEAL_CREATED', 'EXTENSION_APPLIED', 'EXTERNAL_INTEREST_CREATED','EXTERNAL_INTEREST_UPDATED')
hocsprodaudit-> AND a.deleted = false;
QUERY PLAN …
```
> HOCS-4921: Reduce 2/3rds execution time for auditByCaseUUIDAndTypesIn query

- src/main/resources/db/migration/postgresql/V1_11__CREATE_LATEST_EVENTS_INDEX.sql
```
hocsprodaudit=> explain analyze SELECT audit_payload->>'reference' AS caseReference, cast(case_uuid AS VARCHAR(36)) as caseUuid FROM audit_event_latest_events WHERE
type = 'CASE_CREATED' AND case_type = 'b6';
QUERY PLAN                                                              
--------------------------------------------------------------------------------------------------------------------------------------
Seq Scan on audit_event_latest_events  (cost=0.00..59304.05 rows=102330 width=122) (actual time=52.658..167.478 rows=104362 loops=1)
Filter: ((type = 'CASE_CREATED'::text) AND (case_type = 'b6'::text))
Rows Removed by Filter: 392268
Planning Time: 0.147 ms
Execution Time: 171.987 ms
(5 rows)
hocsprodaudit=> create index audit_event_latest_events_case_type on …
```
> Hocs 4980 add index for latest events by case type

- src/main/java/uk/gov/digital/ho/hocs/audit/service/CaseNoteExportService.java
Pass through the missing audit UUID value.
> HOCS-5275: pass through missing value

- src/main/resources/config/case-data-fields.json
Add two new fields to the POGR extract for HMPO ex-gratia screen for the
reason for refund.
> HOCS-5454: add extract fields

- src/main/java/uk/gov/digital/ho/hocs/audit/client/info/dto/SomuTypeField.java
- src/main/java/uk/gov/digital/ho/hocs/audit/service/SomuExportService.java
Retrieve all the required entity lists for each SOMU type and pass to
the converter to support conversion.
> HOCS-5553: handle somu type choices

- src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/CustomExportResource.java
- src/main/java/uk/gov/digital/ho/hocs/audit/service/CustomExportService.java
Add the date on custom export filenames
Only set the response header as attachment providing the export method works
> HOCS-5634 Add date on custom export filenames

- .drone.yml
- helm/hocs-audit.yaml
- helm/hocs-extracts-wcs.yaml
- helm/hocs-extracts.yaml
This would normally be done the other way around with 'dev' changes being tested first.
> HOCS-5561: Match dev to 'notprod' settings

- src/main/resources/config/case-data-fields.json
HOCS-5886:This PR would help to remove 
BF case type gender, DOB & channel when 
the report is extracted.
> Hocs 5886 complaint details screen changes

- src/main/resources/config/case-data-fields.json
HOCS-5958:This PR would help to remove
BF case type gender, DOB & channel when
the report is extracted.
> HOCS-5958:Remove DOB, channel and geneder from case data fields

- src/main/resources/config/case-data-fields.json
HOCS-6666: This PR would help to add BF_WorkInProgress
option for the user and it would populate value as true
if the user picks this in the UI.
> HOCS-6666:Add BF_WorkInProgress to WCS report extracts

- helm/hocs-extracts-wcs.yaml
- helm/hocs-extracts.yaml
HOCS-6913:Rolling back to use keycloak 15 realm
> HOCS-6913:Rolling back to use keycloak 15 realm

- helm/hocs-extracts-wcs.yaml
- helm/hocs-extracts.yaml
Keycloak22 realm url changes added yaml file for dev environment.
> Keycloak22 realm url changes added yaml file
