src/main/resources/application.properties
ACP by default sets maxReceiveCount to 10, but our app sets it to 5.
This commit changes it to match ACP, so we don't keep overwriting each other's configs.
=> HOCS-1057 Match ACP global settings

README.md, src/main/java/uk/gov/digital/ho/hocs/audit/application/ZonedDateTimeConverter.java, src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepository.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/DataExportResource.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java, src/test/java/uk/gov/digital/ho/hocs/audit/ZonedDateTimeConverterTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/DataExportResourceTest.java
On exporting allocations (and any other exports that use the timestamp), we now change the date time to reflect what is current in the Europe/London zone id. Also, now order's by the audit_timestamp by ascending order.
=> Update exported timestamp to show local London time + Order allocations timestamp

src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java
The logs in QA and PROD indicate a null pointer exception, causing the CSV processing to be blanked out completely. Including null pointer exception processing to capture the lines at fault.
=> HOCS-2099 MI Allocations Exception

src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java
Reverts UKHomeOffice/hocs-audit#63
The exception trapping did not provide the required results.
=> Revert "HOCS-2099 MI Allocations Exception"

src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepositoryCustom.java, src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepositoryImpl.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/CustomExportDataConverter.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/CustomExportService.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/DataExportResource.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportIntTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/CustomExportDataConverterTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/CustomExportServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/DataExportResourceTest.java
Currently on the database we pull all the data and then do the 
data conversion. This leads to a big lead time on the download as 
we currently handle this linearly. 
This change makes it so that we stream the data from the custom 
view and thus start building the file as the data comes through.
=> HOCS-2461: change custom reports to stream

src/main/java/uk/gov/digital/ho/hocs/audit/application/ZonedDateTimeConverter.java
Reverts UKHomeOffice/hocs-audit#76
This issue has been resolved and the hotfix has been removed from production.
Reverting as logs no longer required.
=> Revert "HOCS-2424 Add temporary timestamp logging for extract"

src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportDataConverter.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/infoclient/InfoClient.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/infoclient/dto/EntityDataDto.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/infoclient/dto/EntityDto.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/ExportDataConverterTest.java
See https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-2441 "Convert database value to display value in extracts".
Some fields in the audit records store short codes from out entity lists. The requirement here for 3 specific entity lists and for MPAM client only. 
ExportDataConverter now needs to be aware of which client it is converting for, so the client code is now passed in from the ExportService.
=> HOCS-2441 : MPAM entity codes replace with titles

src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepositoryImpl.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/CustomExportService.java
Currently we use the 'getResultStream()' which underneath 
actually does 'getResultList().stream()' which is sequential.
This change is to use the stream directly.
=> HOCS-2461: change implementation to use stream

src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepositoryImpl.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/CustomExportService.java
At present we wait for the first set of data to come through before we start streaming the custom audit file to the user. 
This change flushes the file to the user straight after creating it, bypassing the initial cut off on the file download if the results take longer than 2 minutes to return. 
This PR also lowers the fetch size from 50 to 20 to assist with bringing this down too.
=> HOCS-2624 start streaming file after writing headers

.drone.yml
This change implements the necessary changes 
to use Drone V1 as V0.8 is going to be deprecated. 
Changes include :
- Split build and deploy into two pipelines
- Removed pull request checks
- Changed to push to build_XXX instead of build-XXX
- Added commit sha tag
- Switched to using KUBE_TOKEN as defined in Drone 
rather than the kube repo
- Added acyclic dependency graph for asynchronous build steps
- Made a QA release always release to both QA environments 
consolidated build steps where possible
- Split build step into build and test step
=> HOCS-2672: migrate drone 0.8 to 1

src/main/java/uk/gov/digital/ho/hocs/audit/export/CustomExportService.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/DataExportResource.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/CustomExportServiceTest.java
This change changes the routing so that it doesn't go through keycloak gatekeeper. This then allows us to use basicauth instead of fudging our way around roles and whitelisting the endpoint. As we are not routing the endpoint through Keycloak anymore and the endpoint itself is not external. We also don't need to protect this endpoint anymore.
=> HOCS-2310: change custom export route

.drone.yml, Dockerfile, build.gradle, gradle/wrapper/gradle-wrapper.properties
This pull request contains the following changes: 
- Bring gradle version to latest version
- Change docker image to OpenJDK 11 (in line with other services)
- Bump dependency versions of spring boot and camel 
- Migrate gradle.build to use `implementation` over `compile`
- Change drone pipeline to use OpenJDK 11 for building and testing
=> Java11 migration

.drone.yml, Dockerfile, build.gradle, gradle/wrapper/gradle-wrapper.properties
Issues were identified whereby spring boot would not recognise a 
correct route. As a result the ability to pull reports has been 
compromised. As a result we need to revert this migration while 
further research into the potential migration take place. 
This reverts commit c4bb74226a4681f1667b1c2b1b7b8ade0d7ff0ba.
=> Revert "Java11 migration (#91)"

.drone.yml, Dockerfile, build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/resources/application.properties
At present this service is currently running on Java 8. Although this isn't an issue it means that developers need to have two different JDKs installed to be able to run the service. 
This change brings the service in line with the others to use Java 11. This allows us to leverage Java 11 features going forward and simplifies the tech stack required by the developers working on the system.
The core of this change was previously brought into the main branch as part of #91. This however would not work in our environments due to a change in how Spring Boot 2.1 handles the underlying embedded server. They brought all of the max header sizes in line to a maximum of 8Kb whereas undertow was previously 1Mb. Due to us using the keycloak-gatekeeper to handle authorisation the header size exceeded …
=> HOCS-3120: java11 migration

src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/MalformedDateConverter.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/adapter/DateAdapter.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/infoclient/ExportViewConstants.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/adapter/DateAdapterTest.java
HOCS 3114 Extract Date Format Error
Adapter added for correcting malformed date fields (can be used in custom forms, but not implemented as custom already formats dates).
Implemented date format corrections for all other reports.
Tests added for adapter functionality.
=> Hocs 3114 extract date format error

src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/infoclient/dto/SomuTypeField.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportServiceTest.java
The header for each of the contribution fields that we show now have a
extractColumnLabel that is used for the visual representation. This is
currently present due to the static-ness of the forms and that one field
has an id that does not represent what it is at present.
=> HOCS-3696: use extractColumnLabel

.drone.yml, kube/deploy.sh, kube/kd/autoscale.yaml, kube/kd/deployment.yaml, kube/kd/refreshDcuAggregatedCasesView.yaml, kube/kd/service.yaml
To simplify releases and reduce the chance of configuration changes
unintentionally making its way into production this change brings the
kube repository into the service.
=> HOCS-4030: bring kube into project

.drone.yml
When running the deploy script as we cd into another directory this
fails in the pipeline if you run it from root of the project. This is
because the cd works from the current path you are in. This change
reverts this and adds a `cd kube`.
=> HOCS-4030: reintroduce kd path traversal

build.gradle
While current class-pathing is fast, this change adds the spring context
indexer that speeds this up by creating a list of candidates at
compilation time.
=> HOCS-4073: use spring context indexer

Dockerfile, scripts/run.sh
At present, our current docker strategy is causing image size pollution
and inefficiencies. This is due to us not only using a fat jar strategy
instead of a layered jar, but also because our docker layers are not
cacheable. This change introduces a multi-stage docker build that splits
out the build from the resultant image. In the second stage we then
copy the minimum we require for running the build.
=> HOCS-4073: use docker multi-stage build

src/main/resources/application.yml
Currently, we are not using all the actuator endpoints effectively.
While we are not using them they are still being added to the
application context and cause a start-up penalty. This change disabled
all the endpoints (so we have to opt-in) and then re-enables the health
endpoints.
=> HOCS-4073: improve actuator usage

src/main/resources/logback-spring.xml
Use the defaults logback profile for the logger, at present we are using
the main one that instantiates its own console appender. This leads to
duplicated log messages being printed out to the console.
Presently, we have a number of loggers specified with logback that
aren't needed. These have been removed as they should not be present.
2 new loggers have been specified for xnio and jboss to only log
warnings out.
=> HOCS-4085: rework logstash

kube/kd/deployment.yaml
Added two export user roles for BF and TO. The export endpoints were previously freely accessible by any user.
=> HOCS-4170 add BF and TO export user roles

src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportType.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/converter/ExportDataConverter.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/converter/ExportDataConverterFactory.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/dto/AuditPayload.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/infoclient/InfoClientSupplier.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/parsers/AbstractDataParser.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/parsers/DataParserFactory.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/parsers/interests/AbstractInterestDataParser.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/parsers/interests/BfInterestDataParser.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/parsers/interests/FoiInterestDataParser.java, src/main/java/uk/gov/digital/ho/hocs/audit/utils/UuidStringChecker.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/CaseNoteExportTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/converter/ExportDataConverterTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/infoclient/InfoClientSupplierTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/parsers/DataParserFactoryTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/parsers/interests/BfInterestDataParserTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/parsers/interests/FoiInterestDataParserTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/utils/UuidStringCheckerTest.java
This change implements the CSV writing for interest actions utilising
the new data parser.
To support this new data parser classes have been added, this supports
the simplification of parsing and pritning the data. Typically when users 
run convert on an audit request we spin up a new export data converter
that populates with data that isn't used. This is then ran against all data
rows and columns - and where it matches a UUID not in the mapping
sends a request to casework as it assumes its a case reference. For all 
exports (except CASE_DATA) we know the values that we want to convert
and the values required for the conversion. This data parser acts as the
total send of truth for row conversions, supporting only conversion on 
fields required. 
This change also contains refactoring to …
=> HOCS-4215: implement interest export

kube/kd/deployment.yaml
BF_EXPORT_USER should cover for BF and BF2, so we can remove the BF2 role
=> HOCS-4697 Removes BF2 export role

.drone.yml, .github/workflows/label-check.yml, .github/workflows/semver.yml, LICENSE, README.md
This change removes the use of the old `hocs-version-bot` in favour of
new GitHub actions.
When an action happens on a PR an action is run that checks that the PR
is labeled with one of the following: `Patch`, `Minor`, or `Major`.
If one of these isn't present the PR will be blocked till one is added.
This enables us to immediately identify the scale of the change.
On an successful merge, an second action is ran that uses specified
label to update the SemVer version for the service - automatically
creating a Git Tag with that version.
This triggers a drone build that automatically deploys this new version
to the dev environments.
=> HOCS-4696: use GitHub SemVer actions

.github/dependabot.yml
Since adding the semver labels Dependabot has been adding 'Major', 'Minor' or 'Patch' labels on its PRs according the semver bump on the library it is updating.
We want it to add 'patch' regardless as from our perspective the change is a patch change to the service.
=> HOCS-4696: Override Dependabot lables

src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepository.java, src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepositoryLatestEvents.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/DataExportResource.java, src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java, src/main/resources/db/migration/postgresql/V1_9__CREATE_LATEST_TYPE_TABLE.sql
Introduce a new partitioned table that holds the latest value for
specified types. These partitions mimic the existing partitions on the
`audit_event` table.
This also removes the `toDate` from the required parameters and defaults this
to todays date if not specified. If a user specifies a future date -
this is pegged to todays date within the ExportService to save the
database engine from using non-used dates in its planning time.
=> HOCS-4940: introduce new latest table

src/main/resources/db/migration/postgresql/V1_10__CREATE_LATEST_TABLE_TRIGGERS.sql
Add the latest database triggers that keeps a record of the latest
CASE_UPDATED, CASE_COMPLETED and CASE_CREATED audit reports.
=> HOCS-4940: add latest triggers

src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java, src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportServiceTest.java
Use the audit event latest table for audit events that require only the
lastest type rows. This only runs if the to date is the current date to
ensure valid data. `toDate` in the past still use the old solution.
=> HOCS-4940: use latest table

src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepositoryLatestEvents.java
```
hocsprodaudit=> explain analyze  SELECT a.* FROM audit_event_latest_events a WHERE a.audit_timestamp >= '2022-01-01' AND a.type in ('CASE_CREATED', 'CASE_COMPLETED', 'CASE_UPDATED') AND a.case_type = 'b6' AND a.deleted = false ORDER BY a.case_uuid, a.type, a.audit_timestamp DESC;
QUERY PLAN                                                                                                    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Sort  (cost=65803.06..66064.03 rows=104387 width=752) (actual time=262.438..273.048 rows=91618 loops=1)
Sort Key: case_uuid, type, audit_timestamp DESC
Sort Method: quicksort  Memory: 115663kB …
```
=> HOCS-4921: ~half the execution time for audit_event_latest_events query

src/main/java/uk/gov/digital/ho/hocs/audit/repository/AuditRepository.java, src/main/java/uk/gov/digital/ho/hocs/audit/service/CaseDataExportService.java, src/test/java/uk/gov/digital/ho/hocs/audit/service/CaseDataExportServiceTest.java
There is an issue with the implementation of the streaming with the
`audit_event_latest_events` query whereby upserting information during a
report pull could cause duplicate rows to be returned or missing data.
This change adds row locking when querying this table for the rows that
are returned. This stops any updates to happen while the data is being
read. As queries take less than 1 second on average, this should be more
than enough for most cases.
Improvements to the query have also been added so that inserts after the
report has been started in the database aren't returned - removing
post-added data from causing issues.
=> HOCS-5038: improve latest stream handling

.github/workflows/pr-check.yml, .github/workflows/semver.yml
Change the version to `v1`. While this does mean that we open ourselves
up to potential breaking changes in the action as we currently develop
this ourselves we can ensure changes are done in a way that doesn't
break backwards compatibility.
=> Peg match-label-action to version

config/materializedviews/Audit-Schema-DataUpdates.sql, src/main/java/uk/gov/digital/ho/hocs/audit/service/CustomExportService.java
On the re-write the transactional annotation was incorrectly removed.
This change adds this back in.
Add materialized view creation into `hocs-audit` service. This change
also reworks the creation of these views to minimize any impact changes
to this view have on users.
=> HOCS-5126: materialized view improvements

src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/dto/AuditPayload.java, src/main/java/uk/gov/digital/ho/hocs/audit/service/SuspensionExportService.java, src/main/java/uk/gov/digital/ho/hocs/audit/service/domain/ExportType.java, src/test/java/uk/gov/digital/ho/hocs/audit/service/SuspensionExportServiceTest.java
Add the suspension export report service that allows the user to request
a report based on the types: `CASE_SUSPENSION_APPLIED`,
`CASE_UNSUSPENDED`.
=> HOCS-4995: add suspension export report

kube/kd/deployment.yaml
Change the secret reference to bring in line with the current standard
of `<namespace>-<service>-<rds>`.
=> HOCS-5330: change db secret reference

src/main/resources/config/case-data-fields.json
Remove RefTypeUpdateCount from all extracts apart from 'MPAM'. Remove
PreviousCaseReference from all case types that don't have a previous
case type (non Stage 2).
=> HOCS-4841: remove unnecessary extract fields

src/main/java/uk/gov/digital/ho/hocs/audit/repository/config/model/CaseDataFields.java
At present we are using a base HashSet that while ensures that
duplicates are stripped, does not provide us an exact gauranteed order.
This change changes the underlying collection to use a LinkedHashSet so
that we get the exact order that we specify in the configuration file.
=> Correct case data field reading order

src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/AuditListener.java, src/test/java/uk/gov/digital/ho/hocs/audit/entrypoint/integration/BaseAwsSqsIntegrationTest.java
Change to use the `consumer` profile for listening to the queue rather than the `!extracts`. This allows for the service to opt in to being both a consumer and provider of extracts.
=> Change SQS Listener Profile

src/main/resources/application.yml
Add a Query and Lock timeout for JPA requests, as connections are timed out after 2 minutes, allowing the underlying query to keep a lock and perform computations results in multiple requests causing OOM problems.
=> Add JPA Query and Lock Timeout

src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/AdminResource.java, src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/CustomExportResource.java
Move the `refreshMaterialisedView` method to its own controller not imposed by the `extracts` profile. While this works - the imposed 1 minute timeout kills the underlying refresh.
Moving this to its own controller allows for the main `hocs-audit` deployment to trigger the refresh. This still has the 1 minute timeout applied - but this can be turned off for now.
=> HOCS-6146: move materialised refresh to controller

src/main/java/uk/gov/digital/ho/hocs/audit/repository/AuditRepository.java, src/main/java/uk/gov/digital/ho/hocs/audit/service/CaseDataExportService.java, src/main/resources/db/migration/postgresql/V1_15__REWORK_LATEST_EVENT_TRIGGER_CASE_CREATED.sql, src/test/java/uk/gov/digital/ho/hocs/audit/service/CaseDataExportServiceTest.java
Remove the usage of the latest event table from the CASE_DATA event as
this cannot be run on a read-only replica. This table is still used on
converted extracts.
Repurpose the latest events trigger to only store the CASE_CREATED
events.
=> HOCS-6150: rework audit latest event usage

Dockerfile
In springboot 3.2 the module path for their JarLauncher that we use as an entrypoint has changed.
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#nested-jar-support
https://medium.com/viascom/spring-boot-3-2-x-jarlauncher-path-a3656f8e69b4
=> Change docker entrypoint to org.springframework.boot.loader.launch.JarLauncher

.github/workflows/test.yml, config/materializedviews/Audit-Schema-DataUpdates.sql
Note this will need to be manually applied to environments as the script regenerates the view, which takes too long to be run as a migration during audit service startup
=> [HOCS-7045] Restrict correspondent and comment count CTEs to DCU case types

Dockerfile, build.gradle, config/materializedviews/Audit-Schema-DataUpdates.sql, config/materializedviews/cs-prod-update-audit-materialized-views.yml, config/materializedviews/cs-qa-update-audit-materialized-views.yml, gradle/wrapper/gradle-wrapper.properties, src/main/java/uk/gov/digital/ho/hocs/audit/core/config/sqs/LocalStackConfiguration.java, src/main/java/uk/gov/digital/ho/hocs/audit/core/config/sqs/SqsConfiguration.java, src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/AuditListener.java, src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/CustomExportResource.java, src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/dto/CustomExportFilter.java, src/main/java/uk/gov/digital/ho/hocs/audit/repository/AuditRepositoryCustom.java, src/main/java/uk/gov/digital/ho/hocs/audit/repository/AuditRepositoryImpl.java, src/main/java/uk/gov/digital/ho/hocs/audit/repository/config/model/CustomExportViews.java, src/main/java/uk/gov/digital/ho/hocs/audit/service/CustomExportService.java, src/main/java/uk/gov/digital/ho/hocs/audit/service/domain/converter/CustomExportDataConverter.java, src/main/resources/application-extracts.yml, src/main/resources/application-local.yml, src/main/resources/config/custom-export-views.json, src/test/java/uk/gov/digital/ho/hocs/audit/entrypoint/dto/CustomExportFilterTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/entrypoint/integration/AuditListenerTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/entrypoint/integration/BaseAwsSqsIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/audit/service/domain/converter/CorrespondentUuidToNameCacheTest.java
Firstly this reverts back to the dependency versions used for hocs-audit 3.3.0 that was the last know version that fully works in k8s environments.
[cs-prod-update-audit-materialized-views.yml](https://github.com/UKHomeOffice/hocs-audit/pull/545/files#diff-37dc6ec804c7af4fd0819bb5c6019a5d6e58f8eba39eee8da2d4ddaf5c0018ff) and [cs-qa-update-audit-materialized-views.yml](https://github.com/UKHomeOffice/hocs-audit/pull/545/files#diff-4433f5c7b06c2b045a2a621bcb95d3830aadc5ba9947fa47cec9114cde64a860) are for updating the DCU materialised views using a kubernetes job that were used to deploy [HOCS-7045](https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-7045) and will have future utility when it comes to add the extra indices added by …
=> HOCS-7048--add-filters-to-dcu-custom-reports

config/materializedviews/Audit-Schema-DataUpdates.sql, config/materializedviews/cs-dev-update-audit-materialized-views.yml, config/materializedviews/cs-prod-update-audit-materialized-views.yml, src/main/resources/config/custom-export-views.json
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-7048
> With regards to any additional filters (and if it's not too much trouble), I think having the ability to also filter by caseType, draftingTeam, and draftingUnit might be useful on for handling ad hoc requests for information.
draftingTeam, and draftingUnit will not be added at this time as these values would need to be queried via an API, and they are not guaranteed to be safe to use directly in an SQL query.
=> [HOCS-7048] Add caseType filter to dcu_business export
